name: 发布更新

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    name: 发布更新
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
      - run: pnpm build
      - uses: birchill/edge-addon-upload@98bddd1e08131fba97591e7c998cf488fa73d0f3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          access_token_url: ${{ secrets.EDGE_ACCESS_TOKEN_URL }}
          addon_file: dist/extension.zip
          client_id: ${{ secrets.EDGE_CLIENT_ID }}
          client_secret: ${{ secrets.EDGE_CLIENT_SECRET }}
          product_id: ${{ secrets.EDGE_PRODUCT_ID }}
      - uses: Xotl/cool-github-releases@d181956417d77bcc4b44a812419539893124c6c7
        with:
          mode: update
          tag_name: ${{ github.ref_name }}
          assets: dist/extension.zip
          github_token: ${{ secrets.GITHUB_TOKEN }}
